# Generated by Django 2.1.8 on 2019-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='star',
            field=models.IntegerField(blank=True),
        ),
    ]
