# Generated by Django 2.1.8 on 2019-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190517_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='star',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
